[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
board_build.f_cpu = 240000000
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
debug_speed = 40000
upload_speed = 921600
upload_protocol = esptool
lib_deps =
	knolleary/PubSubClient@^2.8

[env:esp32_ota]
extends = env:esp32
upload_protocol = espota
upload_port = 172.16.8.1
upload_flags =
	--host_port=9938
	--port=3232
	--auth=l13k1nh31t1n!